FROM node:23.11.0 AS builder

WORKDIR /code

COPY package*.json ./

RUN npm install

COPY . /code

RUN npm run build

# Production stage
FROM node:23.11.0-alpine

WORKDIR /code

RUN npm install -g serve

COPY --from=builder /code/dist ./dist

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]