services:
  - type: web
    name: backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    buildCommand: docker build -t backend -f ./backend/Dockerfile .
    startCommand: docker-compose up backend

  - type: web
    name: frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: docker build -t frontend -f ./frontend/Dockerfile .
    startCommand: docker-compose up frontend