version: '3.8'
services:
  app:
    build: .
    container_name: amelkisextra
    volumes:
      - C:\Users\norel_2b285at\Downloads\extra:/code/app
      
      
    ports:
      - "8910:80"
      - "5678:5678"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: unless-stopped