version: '3.8'
services:
  app:
    build: .
    container_name: backend
    volumes:
      - C:\Users\norel_2b285at\Downloads\extra\backend:/code
      
      
    ports:
      - "8998:80"
      - "8998:8998"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: unless-stopped