version: '3.8'
services:
  app:
    build: .
    container_name: backend
    volumes:
      - C:\Users\norel_2b285at\Downloads\extra\backend:/code/app
      
      
    ports:
      - "8999:80"
      - "5678:5678"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: unless-stopped