version: '3.8'
services:
  app:
    build: .
    container_name: amelkisoptimise
    volumes:
      - C:\Users\norel_2b285at\Downloads\optimisation\amelkisaspose\app:/code/app
      
    ports:
      - "8082:80"
      - "5678:5678"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: unless-stopped